//! Newmodem channel-sounding collector.
//!
//! Minimal HTTP pass-through: receives soundings POSTed by the NewModem GUI,
//! verifies an HMAC signature, stores each submission in a folder
//! `<reports_dir>/<YYYY-MM-DD>/<callsign>_<HHMMSS>_<short_hash>/`, and
//! exposes an HTML index that globs that directory.
//!
//! No database: the filesystem IS the source of truth. The admin can
//! `rm -rf` any folder and the index reflects it immediately.

use std::net::SocketAddr;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use axum::{
    body::Bytes,
    extract::{Multipart, Path as AxumPath, State},
    http::{HeaderMap, StatusCode},
    response::{Html, IntoResponse, Redirect, Response},
    routing::{get, post},
    Router,
};
use chrono::{DateTime, Utc};
use clap::Parser;
use hmac::{Hmac, Mac};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use tokio::fs;
use tower_http::services::ServeDir;
use tower_http::trace::TraceLayer;
use tracing::{info, warn};

type HmacSha256 = Hmac<Sha256>;

/// HMAC secret shared with the NewModem GUI. Loaded at build time via
/// `include_str!` from `secret.txt` (gitignored). The repo's
/// `secret.txt.example` only contains a placeholder so `cargo build` works
/// without the real value; copy it to `secret.txt` and put 64 hex chars
/// (256 bits) generated by `openssl rand -hex 32`.
const HMAC_SECRET: &str = include_str!("../secret.txt");

/// Validity window for the timestamp in the HMAC signature, in seconds.
/// Outside this we reject to prevent replays. +/-300 s covers a reasonable
/// client clock drift plus network round-trip.
const TIMESTAMP_WINDOW_SECS: i64 = 300;

#[derive(Parser, Debug)]
#[command(about = "Newmodem channel-sounding collector")]
struct Cli {
    /// Listen address. In prod: 127.0.0.1:8080 behind nginx.
    #[arg(long, default_value = "127.0.0.1:8080")]
    bind: SocketAddr,

    /// Reports storage root. Must be writable by the user running the
    /// binary.
    #[arg(long, default_value = "/var/lib/newmodem-collector/reports")]
    reports_dir: PathBuf,

    /// Max upload size, in megabytes. Guard-rail against abuse.
    #[arg(long, default_value_t = 50)]
    max_upload_mb: usize,
}

#[derive(Clone)]
struct AppState {
    reports_dir: Arc<PathBuf>,
    max_upload_bytes: usize,
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| "newmodem_collector=info,tower_http=info".into()),
        )
        .init();

    let cli = Cli::parse();
    let secret_trimmed = HMAC_SECRET.trim();
    if secret_trimmed.len() < 32 {
        anyhow::bail!(
            "secret.txt too short ({} chars). Generate 64 hex chars via \
             `openssl rand -hex 32`.",
            secret_trimmed.len()
        );
    }
    fs::create_dir_all(&cli.reports_dir).await?;
    info!("storage dir = {}", cli.reports_dir.display());

    let state = AppState {
        reports_dir: Arc::new(cli.reports_dir.clone()),
        max_upload_bytes: cli.max_upload_mb * 1024 * 1024,
    };

    let app = Router::new()
        .route("/", get(index_html))
        .route("/sondage/:date/:folder", get(sondage_detail))
        .route("/api/v1/sondage", post(submit_sondage))
        .route("/api/v1/health", get(health))
        .nest_service(
            "/reports",
            ServeDir::new(cli.reports_dir.clone())
                .precompressed_gzip()
                .precompressed_br(),
        )
        .layer(TraceLayer::new_for_http())
        .with_state(state);

    info!("listening on {}", cli.bind);
    let listener = tokio::net::TcpListener::bind(cli.bind).await?;
    axum::serve(listener, app)
        .with_graceful_shutdown(shutdown_signal())
        .await?;
    Ok(())
}

async fn shutdown_signal() {
    let _ = tokio::signal::ctrl_c().await;
    info!("shutdown signal received");
}

async fn health() -> &'static str {
    "ok\n"
}

// ─────────────────────────────────────────── Submission

/// Main metadata extracted from `metadata.json`; the rest of the JSON is
/// kept as-is on disk but the server only reads these fields for the
/// index. Optional fields = absent so we tolerate future format evolutions.
#[derive(Debug, Clone, Serialize, Deserialize)]
struct ReportMeta {
    callsign: String,
    /// Maidenhead grid locator of the *submitting* station (the one
    /// running the sounder / RX app on its side of the link). For a
    /// sounding, this is the receiver — the transmitter's locator is
    /// in `tx_locator`.
    #[serde(default)]
    locator: Option<String>,
    /// Maidenhead grid locator of the remote TX station, as dictated
    /// by phonie from the far end during the sounding. Only filled by
    /// sounding submissions (RX captures leave it `None`).
    #[serde(default)]
    tx_locator: Option<String>,
    #[serde(default)]
    profile: Option<String>,
    #[serde(default)]
    relay: Option<String>,
    #[serde(default)]
    tx_model: Option<String>,
    #[serde(default)]
    notes: Option<String>,
    #[serde(default)]
    gui_version: Option<String>,
    /// UTC timestamp of the recording on the client side (epoch sec).
    #[serde(default)]
    timestamp: Option<i64>,
}

#[derive(Serialize)]
struct SubmitResponse {
    ok: bool,
    folder: String,
    url: String,
}

async fn submit_sondage(
    State(state): State<AppState>,
    headers: HeaderMap,
    mut multipart: Multipart,
) -> Result<axum::Json<SubmitResponse>, ApiError> {
    // 1. HMAC headers.
    let sig_hex = headers
        .get("x-newmodem-signature")
        .and_then(|v| v.to_str().ok())
        .ok_or_else(|| ApiError::bad("missing X-Newmodem-Signature"))?
        .to_string();
    let ts_str = headers
        .get("x-newmodem-timestamp")
        .and_then(|v| v.to_str().ok())
        .ok_or_else(|| ApiError::bad("missing X-Newmodem-Timestamp"))?;
    let client_ts: i64 = ts_str
        .parse()
        .map_err(|_| ApiError::bad("X-Newmodem-Timestamp not an integer"))?;
    let now_ts = Utc::now().timestamp();
    if (now_ts - client_ts).abs() > TIMESTAMP_WINDOW_SECS {
        return Err(ApiError::bad("timestamp out of window (clock skew?)"));
    }

    // 2. Slurp every multipart field into memory (cap = max_upload_bytes).
    //    For our use case (one sounding = ~a few MB) this is fine, and it
    //    simplifies the HMAC computation which requires concatenated order.
    let mut total = 0usize;
    let mut callsign_field: Option<String> = None;
    let mut metadata_bytes: Option<Bytes> = None;
    let mut report_bytes: Option<Bytes> = None;
    let mut wav_bytes: Option<Bytes> = None;
    let mut png_bytes: Option<Bytes> = None;

    while let Some(field) = multipart
        .next_field()
        .await
        .map_err(|e| ApiError::bad(format!("multipart: {e}")))?
    {
        let name = field.name().unwrap_or("").to_string();
        let data = field
            .bytes()
            .await
            .map_err(|e| ApiError::bad(format!("read field {name}: {e}")))?;
        total = total.saturating_add(data.len());
        if total > state.max_upload_bytes {
            return Err(ApiError::bad(format!(
                "upload too large (> {} MiB)",
                state.max_upload_bytes / (1024 * 1024)
            )));
        }
        match name.as_str() {
            "callsign" => {
                callsign_field = Some(
                    String::from_utf8(data.to_vec())
                        .map_err(|_| ApiError::bad("callsign not utf-8"))?
                        .trim()
                        .to_uppercase(),
                );
            }
            "metadata" => metadata_bytes = Some(data),
            "report" => report_bytes = Some(data),
            "capture_wav" => wav_bytes = Some(data),
            "curves_png" => png_bytes = Some(data),
            other => warn!("ignoring unknown multipart field '{other}'"),
        }
    }

    let callsign = callsign_field.ok_or_else(|| ApiError::bad("missing 'callsign' field"))?;
    if callsign.is_empty() || !callsign.chars().all(|c| c.is_ascii_alphanumeric() || c == '/') {
        return Err(ApiError::bad("callsign must be ASCII alphanumeric (slash allowed)"));
    }
    let metadata_bytes = metadata_bytes.ok_or_else(|| ApiError::bad("missing 'metadata' field"))?;
    let report_bytes = report_bytes.ok_or_else(|| ApiError::bad("missing 'report' field"))?;

    // 3. HMAC: sign `callsign | timestamp | sha256(metadata || report)`.
    //    The binary attachments (wav/png) are not signed: their integrity
    //    is guaranteed by hashes embedded in report.json on the GUI side.
    let body_hash = {
        let mut h = Sha256::new();
        h.update(&metadata_bytes);
        h.update(&report_bytes);
        h.finalize()
    };
    let mut mac = HmacSha256::new_from_slice(HMAC_SECRET.trim().as_bytes())
        .map_err(|_| ApiError::server("HMAC key init failed"))?;
    mac.update(callsign.as_bytes());
    mac.update(b"|");
    mac.update(client_ts.to_string().as_bytes());
    mac.update(b"|");
    mac.update(&body_hash);
    let sig_expected = hex::encode(mac.finalize().into_bytes());
    if !constant_time_eq(sig_expected.as_bytes(), sig_hex.trim().as_bytes()) {
        return Err(ApiError::unauthorized("bad signature"));
    }

    // 4. Parse metadata.json (minimal validation + callsign extraction
    //    for consistency with the field).
    let meta: ReportMeta = serde_json::from_slice(&metadata_bytes)
        .map_err(|e| ApiError::bad(format!("metadata.json parse: {e}")))?;
    if meta.callsign.trim().to_uppercase() != callsign {
        return Err(ApiError::bad("callsign field mismatches metadata.json"));
    }

    // 5. Allocate the folder `<date>/<callsign>_<HHMMSS>_<shorthash>/`.
    //    Date = server-side day (UTC). HHMMSS = server UTC time.
    //    Short hash = first 4 bytes of body_hash, to disambiguate two
    //    simultaneous submissions from the same callsign.
    let now: DateTime<Utc> = Utc::now();
    let date = now.format("%Y-%m-%d").to_string();
    let hhmmss = now.format("%H%M%S").to_string();
    let short = hex::encode(&body_hash[..4]);
    let folder_name = format!("{callsign}_{hhmmss}_{short}");
    let folder_rel = format!("{date}/{folder_name}");
    let folder_abs = state.reports_dir.join(&date).join(&folder_name);
    fs::create_dir_all(&folder_abs)
        .await
        .map_err(|e| ApiError::server(format!("mkdir {}: {e}", folder_abs.display())))?;

    // 6. Write the files.
    write_file(&folder_abs, "metadata.json", &metadata_bytes).await?;
    write_file(&folder_abs, "report.json", &report_bytes).await?;
    if let Some(b) = wav_bytes {
        write_file(&folder_abs, "capture.wav", &b).await?;
    }
    if let Some(b) = png_bytes {
        write_file(&folder_abs, "curves.png", &b).await?;
    }

    info!(
        "stored sondage callsign={} folder={}/{}",
        callsign, date, folder_name
    );

    Ok(axum::Json(SubmitResponse {
        ok: true,
        folder: folder_rel.clone(),
        url: format!("/sondage/{date}/{folder_name}"),
    }))
}

async fn write_file(dir: &Path, name: &str, body: &[u8]) -> Result<(), ApiError> {
    let path = dir.join(name);
    fs::write(&path, body)
        .await
        .map_err(|e| ApiError::server(format!("write {}: {e}", path.display())))
}

// ─────────────────────────────────────────── Index HTML

async fn index_html(State(state): State<AppState>) -> Result<Html<String>, ApiError> {
    let mut entries = Vec::new();
    let mut date_dirs = read_dir_sorted(&state.reports_dir).await?;
    date_dirs.reverse(); // recent dates first
    for date_entry in date_dirs {
        if !date_entry.is_dir {
            continue;
        }
        let date_path = state.reports_dir.join(&date_entry.name);
        let mut sondage_dirs = read_dir_sorted(&date_path).await?;
        sondage_dirs.reverse(); // most recent soundings of the day first
        for sondage in sondage_dirs {
            if !sondage.is_dir {
                continue;
            }
            let meta_path = date_path.join(&sondage.name).join("metadata.json");
            let meta: Option<ReportMeta> = match fs::read(&meta_path).await {
                Ok(b) => serde_json::from_slice(&b).ok(),
                Err(_) => None,
            };
            entries.push(IndexRow {
                date: date_entry.name.clone(),
                folder: sondage.name.clone(),
                meta,
            });
        }
    }
    Ok(Html(render_index(&entries)))
}

struct IndexRow {
    date: String,
    folder: String,
    meta: Option<ReportMeta>,
}

fn render_index(rows: &[IndexRow]) -> String {
    use html_escape::encode_text as h;
    let mut html = String::new();
    html.push_str(INDEX_HEADER);
    html.push_str(&format!(
        "<p class=\"summary\">{} sounding(s) collected.</p>",
        rows.len()
    ));
    if rows.is_empty() {
        html.push_str("<p class=\"empty\">No soundings yet.</p>");
    } else {
        html.push_str("<table><thead><tr>\
            <th>Date</th><th>Callsign</th><th>Profile</th><th>Locator</th>\
            <th>TX</th><th>Relay</th><th>Folder</th></tr></thead><tbody>");
        for row in rows {
            let meta_default = ReportMeta {
                callsign: "?".to_string(),
                locator: None,
                tx_locator: None,
                profile: None,
                relay: None,
                tx_model: None,
                notes: None,
                gui_version: None,
                timestamp: None,
            };
            let m = row.meta.as_ref().unwrap_or(&meta_default);
            let url = format!("/sondage/{}/{}", row.date, row.folder);
            html.push_str(&format!(
                "<tr>\
                    <td><code>{}</code></td>\
                    <td><strong>{}</strong></td>\
                    <td>{}</td>\
                    <td>{}</td>\
                    <td>{}</td>\
                    <td>{}</td>\
                    <td><a href=\"{}\">{}</a></td>\
                </tr>",
                h(&row.date),
                h(&m.callsign),
                h(m.profile.as_deref().unwrap_or("-")),
                h(m.locator.as_deref().unwrap_or("-")),
                h(m.tx_model.as_deref().unwrap_or("-")),
                h(m.relay.as_deref().unwrap_or("-")),
                h(&url),
                h(&row.folder),
            ));
        }
        html.push_str("</tbody></table>");
    }
    html.push_str(INDEX_FOOTER);
    html
}

const INDEX_HEADER: &str = r##"<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<title>NewModem - collected channel soundings</title>
<style>
body{font-family:system-ui,sans-serif;background:#fafafa;color:#222;margin:0;padding:2rem 1.5rem;max-width:1200px;margin:auto;}
h1{color:#2b7fbf;border-bottom:3px solid #2b7fbf;padding-bottom:.4rem;}
.summary{color:#666;}
table{width:100%;border-collapse:collapse;margin-top:1rem;font-size:.92rem;}
th,td{border:1px solid #ddd;padding:.45rem .6rem;text-align:left;}
th{background:#eef6ff;color:#2b7fbf;}
tr:hover{background:#f5f9fc;}
code{background:#f3f3f3;padding:.1em .3em;border-radius:3px;font-family:Consolas,monospace;}
a{color:#2b7fbf;text-decoration:none;}
a:hover{text-decoration:underline;}
.empty{color:#999;font-style:italic;}
footer{margin-top:3rem;color:#999;font-size:.85rem;}
</style></head><body>
<h1>NewModem - collected channel soundings</h1>
"##;

const INDEX_FOOTER: &str = r##"<footer>
Raw filesystem storage: <code>/var/lib/newmodem-collector/reports/</code>.
Bin: <a href="/api/v1/health">/api/v1/health</a>.
</footer></body></html>
"##;

// ─────────────────────────────────────────── Sondage detail

async fn sondage_detail(
    State(state): State<AppState>,
    AxumPath((date, folder)): AxumPath<(String, String)>,
) -> Response {
    if !is_safe_segment(&date) || !is_safe_segment(&folder) {
        return ApiError::bad("invalid path").into_response();
    }
    let dir = state.reports_dir.join(&date).join(&folder);
    let meta_path = dir.join("metadata.json");
    let meta_bytes = match fs::read(&meta_path).await {
        Ok(b) => b,
        Err(_) => return Redirect::to("/").into_response(),
    };
    let meta: ReportMeta = match serde_json::from_slice(&meta_bytes) {
        Ok(m) => m,
        Err(_) => {
            return ApiError::server("metadata.json corrupted").into_response();
        }
    };
    let mut files = Vec::new();
    if let Ok(mut rd) = fs::read_dir(&dir).await {
        while let Ok(Some(ent)) = rd.next_entry().await {
            let name = ent.file_name().to_string_lossy().to_string();
            files.push(name);
        }
    }
    files.sort();

    use html_escape::encode_text as h;
    let mut html = String::new();
    html.push_str(INDEX_HEADER);
    html.push_str(&format!(
        "<p><a href=\"/\">&larr; back to index</a></p>\
         <h2>{} - {}</h2>\
         <table><tr><th>Field</th><th>Value</th></tr>\
         <tr><td>Callsign</td><td><strong>{}</strong></td></tr>\
         <tr><td>Profile</td><td>{}</td></tr>\
         <tr><td>Locator</td><td>{}</td></tr>\
         <tr><td>TX</td><td>{}</td></tr>\
         <tr><td>Relay</td><td>{}</td></tr>\
         <tr><td>Notes</td><td>{}</td></tr>\
         <tr><td>GUI version</td><td>{}</td></tr>\
         </table>",
        h(&date),
        h(&folder),
        h(&meta.callsign),
        h(meta.profile.as_deref().unwrap_or("-")),
        h(meta.locator.as_deref().unwrap_or("-")),
        h(meta.tx_model.as_deref().unwrap_or("-")),
        h(meta.relay.as_deref().unwrap_or("-")),
        h(meta.notes.as_deref().unwrap_or("-")),
        h(meta.gui_version.as_deref().unwrap_or("-")),
    ));
    html.push_str("<h3>Files</h3><ul>");
    for f in &files {
        let url = format!("/reports/{date}/{folder}/{f}");
        html.push_str(&format!(
            "<li><a href=\"{}\">{}</a></li>",
            h(&url),
            h(f)
        ));
    }
    html.push_str("</ul>");
    html.push_str(INDEX_FOOTER);
    Html(html).into_response()
}

fn is_safe_segment(s: &str) -> bool {
    !s.is_empty()
        && !s.contains("..")
        && !s.contains('/')
        && !s.contains('\\')
        && s.chars().all(|c| c.is_ascii_graphic())
}

// ─────────────────────────────────────────── Helpers

struct DirEntryInfo {
    name: String,
    is_dir: bool,
}

async fn read_dir_sorted(dir: &Path) -> Result<Vec<DirEntryInfo>, ApiError> {
    let mut out = Vec::new();
    let mut rd = match fs::read_dir(dir).await {
        Ok(rd) => rd,
        Err(_) => return Ok(out),
    };
    while let Ok(Some(ent)) = rd.next_entry().await {
        let name = ent.file_name().to_string_lossy().to_string();
        let ft = ent
            .file_type()
            .await
            .map_err(|e| ApiError::server(format!("file_type: {e}")))?;
        out.push(DirEntryInfo {
            name,
            is_dir: ft.is_dir(),
        });
    }
    out.sort_by(|a, b| a.name.cmp(&b.name));
    Ok(out)
}

fn constant_time_eq(a: &[u8], b: &[u8]) -> bool {
    if a.len() != b.len() {
        return false;
    }
    let mut diff = 0u8;
    for (x, y) in a.iter().zip(b.iter()) {
        diff |= x ^ y;
    }
    diff == 0
}

// ─────────────────────────────────────────── Errors

struct ApiError {
    status: StatusCode,
    msg: String,
}

impl ApiError {
    fn bad(msg: impl Into<String>) -> Self {
        Self {
            status: StatusCode::BAD_REQUEST,
            msg: msg.into(),
        }
    }
    fn unauthorized(msg: impl Into<String>) -> Self {
        Self {
            status: StatusCode::UNAUTHORIZED,
            msg: msg.into(),
        }
    }
    fn server(msg: impl Into<String>) -> Self {
        Self {
            status: StatusCode::INTERNAL_SERVER_ERROR,
            msg: msg.into(),
        }
    }
}

impl IntoResponse for ApiError {
    fn into_response(self) -> Response {
        warn!(status = self.status.as_u16(), "{}", self.msg);
        (self.status, format!("{}\n", self.msg)).into_response()
    }
}
