//! Preamble generation: 256 QPSK symbols.
//!
//! Three distinct sequences (`PreambleFamily::{A, B, C}`) are provided so
//! that the receiver-side FFT gate can identify the on-air profile family
//! from a single cross-correlation pass — without paying the matched-filter
//! cost of a 5-profile sweep through `detect_best_profile`.
//!
//! Mapping (driven by `ModemConfig::preamble_family()`) :
//!   - **Family A** : `(sps=32, β=0.20)` — NORMAL, HIGH, MEGA.
//!     Numpy `RandomState(1234).randint(0, 4, 256)`. The legacy preamble :
//!     all profiles emitted this before the family split (kept as-is so
//!     NORMAL/HIGH/MEGA OTA captures from old TX builds still decode).
//!   - **Family B** : `(sps=48, β=0.25)` — ROBUST. Generated by a
//!     deterministic Rust LCG seeded at 0x5678_9012_3456_789A.
//!   - **Family C** : `(sps=96, β=0.25)` — ULTRA. Same LCG seeded at
//!     0x9ABC_DEF0_1234_5678.
//!
//! Each pair of families has cross-correlation ≪ auto-correlation (random
//! sequences of 256 QPSK symbols : auto-corr peak = 256, cross-corr ≈ √256
//! = 16 RMS) — far enough apart for the gate to disambiguate cleanly.

use std::f64::consts::PI;
use std::sync::OnceLock;

use crate::types::{Complex64, N_PREAMBLE};

/// Identifies which preamble sequence is in use. Selected by the TX based
/// on its profile family (`ModemConfig::preamble_family()`) and used by
/// the RX gate to classify the on-air signal in a single FFT pass.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum PreambleFamily {
    /// `(sps=32, β=0.20)` : NORMAL / HIGH / MEGA. Numpy-RandomState seed 1234.
    A = 0,
    /// `(sps=48, β=0.25)` : ROBUST. LCG seed 0x5678_9012_3456_789A.
    B = 1,
    /// `(sps=96, β=0.25)` : ULTRA. LCG seed 0x9ABC_DEF0_1234_5678.
    C = 2,
}

impl PreambleFamily {
    pub const ALL: [Self; 3] = [Self::A, Self::B, Self::C];

    pub fn name(self) -> &'static str {
        match self {
            Self::A => "A",
            Self::B => "B",
            Self::C => "C",
        }
    }
}

/// Simple LCG matching numpy.random.RandomState behaviour for randint(0,4).
///
/// numpy RandomState uses MT19937 which is complex. Instead we reproduce the
/// exact output sequence by hardcoding: the Python code does
/// `rng = np.random.RandomState(1234); q = rng.randint(0, 4, 256)`.
/// We store the known sequence to guarantee cross-platform compatibility.
///
/// Generated with: `np.random.RandomState(1234).randint(0, 4, 256).tolist()`
const PREAMBLE_PHASES: [u8; 256] = [
    3, 3, 2, 1, 0, 0, 0, 1, 3, 1, 3, 1, 2, 2, 3, 2,
    0, 0, 2, 2, 2, 0, 0, 0, 1, 0, 1, 3, 2, 2, 3, 2,
    0, 3, 0, 1, 2, 2, 2, 3, 3, 3, 0, 1, 3, 0, 3, 2,
    3, 0, 1, 3, 3, 3, 2, 1, 2, 3, 3, 0, 2, 3, 2, 0,
    1, 3, 1, 0, 0, 0, 1, 1, 1, 3, 1, 3, 1, 0, 1, 0,
    1, 0, 1, 0, 0, 0, 2, 0, 2, 0, 2, 3, 3, 1, 2, 1,
    2, 2, 1, 1, 2, 3, 0, 3, 1, 2, 3, 2, 0, 2, 3, 3,
    2, 2, 0, 0, 2, 3, 1, 3, 3, 2, 3, 2, 1, 2, 3, 0,
    1, 0, 1, 2, 1, 2, 1, 2, 1, 1, 1, 3, 0, 3, 3, 1,
    2, 0, 0, 1, 0, 1, 2, 1, 1, 2, 3, 2, 0, 1, 1, 1,
    3, 2, 0, 0, 3, 0, 0, 2, 0, 0, 0, 0, 1, 0, 2, 1,
    3, 0, 2, 0, 3, 2, 2, 3, 3, 2, 2, 1, 3, 0, 0, 1,
    1, 2, 2, 3, 1, 0, 3, 2, 0, 1, 1, 1, 0, 0, 1, 3,
    3, 0, 0, 0, 1, 1, 0, 2, 3, 1, 1, 2, 1, 3, 3, 3,
    1, 3, 0, 0, 1, 0, 1, 3, 2, 1, 1, 2, 2, 2, 1, 0,
    3, 0, 0, 0, 0, 0, 3, 3, 1, 1, 1, 2, 1, 3, 1, 3,
];

/// Build a QPSK preamble symbol from a phase index `q ∈ {0,1,2,3}`.
fn phase_to_qpsk(q: u8) -> Complex64 {
    let angle = PI / 4.0 + (q & 3) as f64 * PI / 2.0;
    Complex64::new(angle.cos(), angle.sin())
}

/// Family A — legacy preamble (Numpy seed 1234), used by NORMAL / HIGH / MEGA.
pub fn make_preamble() -> Vec<Complex64> {
    PREAMBLE_PHASES.iter().map(|&q| phase_to_qpsk(q)).collect()
}

/// Build the family-specific preamble. The result is cached after first
/// call (families B and C are generated at runtime via a deterministic LCG ;
/// family A is the legacy hardcoded numpy sequence). Each family returns
/// 256 unit-circle QPSK symbols.
pub fn make_preamble_for(family: PreambleFamily) -> Vec<Complex64> {
    match family {
        PreambleFamily::A => family_a().clone(),
        PreambleFamily::B => family_b().clone(),
        PreambleFamily::C => family_c().clone(),
    }
}

/// Build the family preamble scaled by `config.preamble_amplitude()`.
///
/// Pour la plupart des profils l'amplitude est 1.0 → équivalent strict à
/// `make_preamble_for(family)`. Pour Apsk64 (HIGH++) le QPSK unitaire est
/// multiplié par R4 pour atterrir sur les 4 points outer-ring de la
/// constellation (indices 0/1/2/3 de la Table 13e EN 302 307-2),
/// garantissant la continuité d'échelle FFE/LMS preamble→data.
///
/// Le TX et le RX appellent tous deux cette fonction → l'échelle est
/// cohérente sans renégociation.
pub fn make_preamble_for_config(config: &crate::profile::ModemConfig) -> Vec<Complex64> {
    let base = make_preamble_for(config.preamble_family());
    let amp = config.training_amplitude();
    if (amp - 1.0).abs() < 1e-9 {
        return base;
    }
    base.into_iter().map(|s| s * amp).collect()
}

/// Séquence de « guard interval LMS » insérée entre préambule QPSK et
/// header pour que le FFE adapte au mu_train sur la constellation data
/// avant de basculer en DD.
///
/// Pour les profils non-Apsk64 : Vec vide (le préambule QPSK et la
/// transition DD-on-data-constellation suffisaient — c'est le
/// comportement historique).
///
/// Pour Apsk64 (HIGH++) : 64 symboles balayant **chaque point de la
/// constellation 4+12+20+28 exactement une fois** (indices 0..63 dans
/// l'ordre canonique de la Table 13e). LMS voit toutes les amplitudes
/// (R1..R4) et tous les angles avant la première CW data, donc le meta
/// CW arrive sur un FFE déjà adapté à la densité.
///
/// La séquence est déterministe et se reconstitue identiquement TX↔RX.
pub fn make_lms_warmup_for_config(config: &crate::profile::ModemConfig) -> Vec<Complex64> {
    let n = config.lms_warmup_syms();
    if n == 0 {
        return Vec::new();
    }
    let constellation = crate::frame::make_constellation(config);
    // Sweep canonique : indice 0..n (mod 64). Pour HIGH++ avec n=64 →
    // chaque point exactement une fois, dans l'ordre de la table.
    (0..n)
        .map(|k| constellation.points[k % constellation.points.len()])
        .collect()
}

fn family_a() -> &'static Vec<Complex64> {
    static V: OnceLock<Vec<Complex64>> = OnceLock::new();
    V.get_or_init(make_preamble)
}

fn family_b() -> &'static Vec<Complex64> {
    static V: OnceLock<Vec<Complex64>> = OnceLock::new();
    V.get_or_init(|| build_with_lcg_seed(0x5678_9012_3456_789A))
}

fn family_c() -> &'static Vec<Complex64> {
    static V: OnceLock<Vec<Complex64>> = OnceLock::new();
    V.get_or_init(|| build_with_lcg_seed(0x9ABC_DEF0_1234_5678))
}

/// Numerical-Recipes-style LCG (Knuth's MMIX constants), draws 256 QPSK
/// phases from a single u64 seed. Picks the high 2 bits of each LCG output
/// (good entropy region) and folds into `{0,1,2,3}`.
///
/// Deterministic — same seed always produces the same sequence regardless
/// of platform, optimiser, or rustc version.
fn build_with_lcg_seed(seed: u64) -> Vec<Complex64> {
    let mut state = seed;
    let mut out = Vec::with_capacity(N_PREAMBLE);
    for _ in 0..N_PREAMBLE {
        state = state
            .wrapping_mul(6364136223846793005)
            .wrapping_add(1442695040888963407);
        let q = ((state >> 62) & 3) as u8;
        out.push(phase_to_qpsk(q));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn preamble_length() {
        assert_eq!(make_preamble().len(), crate::types::N_PREAMBLE);
    }

    #[test]
    fn preamble_unit_circle() {
        for s in make_preamble() {
            assert!((s.norm() - 1.0).abs() < 1e-12);
        }
    }

    #[test]
    fn preamble_deterministic() {
        let p1 = make_preamble();
        let p2 = make_preamble();
        for (a, b) in p1.iter().zip(p2.iter()) {
            assert_eq!(a, b);
        }
    }

    #[test]
    fn preamble_seed_matches() {
        // Verify the seed constant is what we expect
        assert_eq!(crate::types::PREAMBLE_SEED, 1234);
    }

    #[test]
    fn families_are_distinct() {
        // Auto-correlation : 256. Cross-correlation between two random
        // QPSK sequences of length 256 has RMS ≈ √256 = 16. We require
        // that the cross-correlation magnitude (worst over alignment 0)
        // be far below 256, confirming the families are well-separated.
        let a = make_preamble_for(PreambleFamily::A);
        let b = make_preamble_for(PreambleFamily::B);
        let c = make_preamble_for(PreambleFamily::C);

        let inner = |x: &[Complex64], y: &[Complex64]| -> f64 {
            x.iter()
                .zip(y.iter())
                .map(|(a, b)| (a.conj() * b))
                .sum::<Complex64>()
                .norm()
        };

        let auto = inner(&a, &a);
        assert!((auto - 256.0).abs() < 1e-6, "auto-corr A != 256 ({})", auto);

        let cross_ab = inner(&a, &b);
        let cross_ac = inner(&a, &c);
        let cross_bc = inner(&b, &c);
        for (lbl, v) in [("A·B", cross_ab), ("A·C", cross_ac), ("B·C", cross_bc)] {
            // Worst-case acceptable cross-correlation : peak / 4 = 64. In
            // practice the LCG-seeded sequences land around 10–40.
            assert!(
                v < 64.0,
                "cross-corr {lbl} = {:.1} too high (need < 64, auto = {auto})",
                v
            );
        }
    }

    #[test]
    fn families_are_deterministic() {
        // Calling `make_preamble_for` twice must produce identical bytes —
        // sequence values are baked into the binary semantics, OTA bursts
        // depend on cross-build stability.
        for &fam in &PreambleFamily::ALL {
            let a = make_preamble_for(fam);
            let b = make_preamble_for(fam);
            assert_eq!(a.len(), N_PREAMBLE);
            for (x, y) in a.iter().zip(b.iter()) {
                assert_eq!(x, y);
            }
        }
    }

    #[test]
    fn make_preamble_equals_family_a() {
        let legacy = make_preamble();
        let fam_a = make_preamble_for(PreambleFamily::A);
        assert_eq!(legacy, fam_a);
    }
}
